language: android
jdk: oraclejdk8
notifications:
  email:
    - external-ci-notifications+popup-bridge-android@getbraintree.com
sudo: true
android:
  components:
    - tools
    - android-26
    - android-22
    - build-tools-26.0.0
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-26
before_script:
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script: ./gradlew clean lint test connectedAndroidTest
after_success: ./deploy_snapshot.sh
